from pathlib import Path

ROOT=Path(__file__).resolve().parents[2]
p=ROOT/'mt5_bridge/event_core/engine.py'
text=p.read_text(encoding='utf-8')
old="""        if self.last_market_attempt<0 or now-self.last_market_attempt>=1:\n            self.last_market_attempt=now;self.bar_errors=[]\n            for attr,tf in (('bars',self.config.timeframe),('context',CONTEXT[self.config.timeframe])):\n                try:\n                    values=list(self.broker.bars(symbol,tf))\n                    if not values:\n                        raise Blocked('MT5 вернул пустую историю '+tf)\n                    ordered(values)\n                    if tf!='MN1' and values[-1].time+TF_SECONDS[tf]>now:\n                        raise Blocked('MT5 вернул незакрытую свечу '+tf)\n                    setattr(self,attr,values)\n                except Exception as exc:\n                    self.bar_errors.append('История '+tf+' не обновлена: '+str(exc))\n            if not self.bar_errors:\n                self.last_bars_at=now;self.market_time=now\n"""
new="""        if self.last_market_attempt<0 or now-self.last_market_attempt>=1:\n            self.last_market_attempt=now;self.bar_errors=[]\n            if self.config.timeframe=='M5':\n                # R3 reads each context independently. Swing logic sees CLOSED bars only;\n                # the forming M5 candle is isolated for the live IMPULSE detector.\n                layers=(('bars','M5'),('m1','M1'),('m15','M15'),('h1','H1'))\n            else:\n                layers=(('bars',self.config.timeframe),('context',CONTEXT[self.config.timeframe]))\n            for attr,tf in layers:\n                try:\n                    values=list(self.broker.bars(symbol,tf))\n                    if not values:\n                        raise Blocked('MT5 вернул пустую историю '+tf)\n                    ordered(values)\n                    if tf!='MN1' and values[-1].time+TF_SECONDS[tf]>now:\n                        raise Blocked('MT5 вернул незакрытую свечу '+tf)\n                    setattr(self,attr,values)\n                except Exception as exc:\n                    self.bar_errors.append('История '+tf+' не обновлена: '+str(exc))\n            if self.config.timeframe=='M5':\n                self.context=self.m15\n                try:\n                    self.live_bar=self.broker.current_bar(symbol,'M5')\n                    if self.live_bar.time>now+1:\n                        raise Blocked('MT5 вернул текущую M5 свечу из будущего')\n                except Exception as exc:\n                    self.live_bar=None\n                    self.bar_errors.append('Текущая M5 свеча не обновлена: '+str(exc))\n            else:\n                self.m1=[];self.m15=[];self.h1=[];self.live_bar=None\n            if not self.bar_errors:\n                self.last_bars_at=now;self.market_time=now\n"""
if text.count(old)!=1:
    raise SystemExit('R3 market refresh block not found exactly once')
p.write_text(text.replace(old,new,1),encoding='utf-8')
